name: Push Events Test

run-name: Push Events Test ${{ github.event_name }} on ${{ github.ref_name }}

on:
  push:
  workflow_dispatch:

jobs:
  deployment-job:    
    name: Event Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Push Event Test
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: 
          python src/push_events_test.py