
name: Demo Launcher
run-name: Running Demo ${{inputs.demo_name}}

on:
  workflow_dispatch:
    inputs:
      demo_name:
        type: choice
        description: Demo to run
        options: 
        - demo_01
        - demo_02
        - demo_03
        - demo_04
        - demo_05
        - demo_06
        - demo_07
        - demo_08

jobs:
  deployment-job:
    name: Run Demo - ${{inputs.demo_name}}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install MSAL
        run: |
          pip install msal

      - name: Run Demo
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
          FABRIC_CAPACITY_ID: ${{ secrets.FABRIC_CAPACITY_ID }}       
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          SOLUTION_NAME: ${{inputs.solution_name}}    
        run: 
          python src/${{inputs.demo_name}}.py