
name: Demo Script Launcher
run-name: Running ${{inputs.demo_name}}

on:
  workflow_dispatch:
    inputs:
      demo_name:
        type: choice
        description: Demo to run
        options: 
        - demo_01 - Get Access Token for Service Principal
        - demo_03 - Get Access Token for User using Device Code
        - demo_04 - Execute Fabric REST API Call to List Workspaces
        - demo_05 - Execute Fabric REST API Call to List Capacities
        - demo_06 - Execute Fabric REST API to Create Workspace
        - demo_07 - Create Workspace using FabricRestApi Class
        - demo_08 - Deploy Complete Fabric Solution

jobs:
  deployment-job:
    name: Run Demo - ${{inputs.demo_name}}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install MSAL
        run: |
          pip install msal

      - name: Run Demo
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
          FABRIC_CAPACITY_ID: ${{ secrets.FABRIC_CAPACITY_ID }}       
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
        run: 
          python 'src/${{ inputs.demo_name }}.py'

          