
name: Deploy Solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        type: choice
        description: Solution to deploy
        options: 
        - Power BI Solution
        - Notebook Solution
      workspace_name:
        description: Name for new workspace
        required: true
        default: Custom Solution 99
      repo_name:
        description: give it a try
        default: ${{ inputs.deploy_target }} by @${{ github.actor }}

jobs:
  deployment-job:    
    name: Deploy Fabric Solution
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install MSAL
        run: |
          pip install msal

      - name: Deploy Solution        
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
        run: 
          python src/deploy_solution.py