
name: Deploy Solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        type: choice
        description: Solution to deploy
        options: 
        - Custom Power BI Solution
        - Custom Notebook Solution
        - Custom Shortcut Solution
        - Custom Data Pipeline Solution

jobs:
  deployment-job:    
    name: Deploy Fabric Solution
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install MSAL
        run: |
          pip install msal

      - name: Deploy Solution        
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
          FABRIC_CAPACITY_ID: ${{ secrets.FABRIC_CAPACITY_ID }}       
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}             
        run: 
          python src/deploy_solution.py