
name: Task - Cleanup Environment

on:
  workflow_dispatch:

jobs:
  deployment-job:    
    name: Cleanup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install MSAL
        run: |
          pip install msal

      - name: Cleanup Environment        
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}          
          FABRIC_CAPACITY_ID: ${{ secrets.FABRIC_CAPACITY_ID }}       
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: 
          python src/task_cleanup_environment.py